language: python
python:
  - "3.6"
# command to install dependencies

addons:
  sonarcloud:
    organization: "jacques15" # the key of the org you chose at step #3
    
install:
  - pip install -U flask
  - nvm install 10
# command to run tests
script:
  - python app.py
  
  